```
```
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    middle_name character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT customers_pkey PRIMARY KEY (customer_id),
    CONSTRAINT customers_email_key UNIQUE (email),
    CONSTRAINT customers_phone_key UNIQUE (phone)
);

COMMENT ON TABLE public.customers
    IS 'Таблица заказчиков строительных проектов';

COMMENT ON COLUMN public.customers.last_name
    IS 'Фамилия заказчика';

COMMENT ON COLUMN public.customers.first_name
    IS 'Имя заказчика';

COMMENT ON COLUMN public.customers.middle_name
    IS 'Отчество заказчика';

CREATE TABLE IF NOT EXISTS public.foremen
(
    foreman_id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(50) COLLATE pg_catalog."default" NOT NULL,
    supervisor_phone character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    middle_name character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT foremen_pkey PRIMARY KEY (foreman_id),
    CONSTRAINT foremen_email_key UNIQUE (email),
    CONSTRAINT foremen_phone_key UNIQUE (phone)
);

COMMENT ON TABLE public.foremen
    IS 'Таблица бригадиров/прорабов';

COMMENT ON COLUMN public.foremen.supervisor_phone
    IS 'Телефон руководителя для экстренной связи';

COMMENT ON COLUMN public.foremen.last_name
    IS 'Фамилия бригадира';

COMMENT ON COLUMN public.foremen.first_name
    IS 'Имя бригадира';

COMMENT ON COLUMN public.foremen.middle_name
    IS 'Отчество бригадира';

CREATE TABLE IF NOT EXISTS public.materials
(
    material_id serial NOT NULL,
    task_id integer NOT NULL,
    material_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(10, 2) NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    receipt_photo_base64 text COLLATE pg_catalog."default",
    purchase_date date NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT materials_pkey PRIMARY KEY (material_id)
);

COMMENT ON TABLE public.materials
    IS 'Таблица материалов для задач';

COMMENT ON COLUMN public.materials.receipt_photo_base64
    IS 'Фото чека в формате Base64';

CREATE TABLE IF NOT EXISTS public.media
(
    media_id serial NOT NULL,
    task_id integer NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_data_base64 text COLLATE pg_catalog."default" NOT NULL,
    file_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    file_size integer NOT NULL,
    upload_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    description text COLLATE pg_catalog."default",
    uploaded_by integer,
    CONSTRAINT media_pkey PRIMARY KEY (media_id)
);

COMMENT ON TABLE public.media
    IS 'Таблица медиафайлов задач (фото/видео)';

COMMENT ON COLUMN public.media.file_data_base64
    IS 'Данные файла в формате Base64';

COMMENT ON COLUMN public.media.file_type
    IS 'MIME-тип файла (image/jpeg, video/mp4, etc.)';

CREATE TABLE IF NOT EXISTS public.projects
(
    project_id serial NOT NULL,
    project_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_id integer NOT NULL,
    foreman_id integer NOT NULL,
    budget numeric(15, 2) NOT NULL,
    spent_budget numeric(15, 2)